import Foundation

/// A stable identifier for a snapshot.
public struct SnapshotID: RawRepresentable, Sendable, Hashable, Codable, Comparable, CustomStringConvertible,
    Identifiable {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init() {
        rawValue = UUID().uuidString
    }

    public var description: String {
        rawValue
    }

    public var id: String {
        rawValue
    }

    /// A short prefix suitable for CLI output, in the spirit of a Git short SHA.
    public var shortValue: String {
        String(rawValue.replacingOccurrences(of: "-", with: "").prefix(8)).lowercased()
    }

    public static func < (lhs: SnapshotID, rhs: SnapshotID) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

extension SnapshotID: ExpressibleByStringLiteral {
    public init(stringLiteral value: String) {
        self.init(rawValue: value)
    }
}

/// Why a snapshot exists.
public enum SnapshotOrigin: String, Sendable, Hashable, Codable, CaseIterable {
    /// The user pressed the button.
    case manual

    /// Produced by the scheduler.
    case scheduled

    /// Produced in response to a system event, e.g. waking from sleep.
    case triggered

    /// Read in from another device's export.
    case imported

    /// Generated by tests or fixtures.
    case synthetic

    public var displayName: String {
        switch self {
        case .manual: "Manual snapshot"
        case .scheduled: "Scheduled snapshot"
        case .triggered: "Automatic snapshot"
        case .imported: "Imported snapshot"
        case .synthetic: "Synthetic snapshot"
        }
    }

    public var symbol: String {
        switch self {
        case .manual: "hand.tap"
        case .scheduled: "clock"
        case .triggered: "bolt"
        case .imported: "square.and.arrow.down"
        case .synthetic: "testtube.2"
        }
    }
}

/// Identifies the device a snapshot came from, without identifying the user.
public struct DeviceIdentity: Sendable, Hashable, Codable {
    /// A stable per-install identifier. Not a hardware serial.
    public let id: String
    public var name: String
    public var model: String
    public var systemName: String
    public var systemVersion: String
    public var architecture: String

    public init(
        id: String,
        name: String,
        model: String,
        systemName: String,
        systemVersion: String,
        architecture: String
    ) {
        self.id = id
        self.name = name
        self.model = model
        self.systemName = systemName
        self.systemVersion = systemVersion
        self.architecture = architecture
    }

    public static let unknown = DeviceIdentity(
        id: "unknown",
        name: "Unknown device",
        model: "unknown",
        systemName: "unknown",
        systemVersion: "0",
        architecture: "unknown"
    )
}

/// Bookkeeping attached to a snapshot that is not itself observed state.
public struct SnapshotMetadata: Sendable, Hashable, Codable {
    /// Version of Diffuse that produced the snapshot.
    public var appVersion: SemanticVersion

    /// Total wall-clock time spent collecting.
    public var collectionDuration: TimeInterval

    /// The redaction policy already applied to the contents, if any.
    public var appliedRedaction: RedactionPolicy

    /// Capabilities that were deliberately not run.
    public var skippedCapabilities: [CapabilityID]

    public init(
        appVersion: SemanticVersion = "1.0.0",
        collectionDuration: TimeInterval = 0,
        appliedRedaction: RedactionPolicy = .none,
        skippedCapabilities: [CapabilityID] = []
    ) {
        self.appVersion = appVersion
        self.collectionDuration = collectionDuration
        self.appliedRedaction = appliedRedaction
        self.skippedCapabilities = skippedCapabilities
    }
}

/// An immutable record of observed device state at a single point in time.
///
/// Snapshots are never edited after they are saved. Retaking a snapshot creates
/// a new one; the history is append-only, which is what gives Diffuse its
/// Git-like model. The only mutable fields are user annotations (`label`,
/// `note`, `isPinned`, `tags`), which are metadata *about* the snapshot rather
/// than part of the observation itself.
public struct Snapshot: Sendable, Hashable, Codable, Identifiable {
    public let id: SnapshotID
    public let schemaVersion: SchemaVersion
    public let capturedAt: Date
    public let platform: Platform
    public let device: DeviceIdentity
    public let origin: SnapshotOrigin

    /// User-supplied name, e.g. "Before installing Node".
    public var label: String?
    public var note: String?

    /// Pinned snapshots survive automatic retention cleanup.
    public var isPinned: Bool
    public var tags: Set<String>

    public var sections: [SnapshotSection]
    public var metadata: SnapshotMetadata

    public init(
        id: SnapshotID = SnapshotID(),
        schemaVersion: SchemaVersion = .current,
        capturedAt: Date,
        platform: Platform,
        device: DeviceIdentity,
        origin: SnapshotOrigin = .manual,
        label: String? = nil,
        note: String? = nil,
        isPinned: Bool = false,
        tags: Set<String> = [],
        sections: [SnapshotSection] = [],
        metadata: SnapshotMetadata = SnapshotMetadata()
    ) {
        self.id = id
        self.schemaVersion = schemaVersion
        self.capturedAt = capturedAt.roundedForSnapshot()
        self.platform = platform
        self.device = device
        self.origin = origin
        self.label = label
        self.note = note
        self.isPinned = isPinned
        self.tags = tags
        self.sections = sections
        self.metadata = metadata
    }

    // MARK: - Derived

    /// The name shown in timelines, falling back to the capture time.
    public var displayName: String {
        if let label, !label.isEmpty {
            return label
        }
        return capturedAt.formatted(date: .omitted, time: .shortened)
    }

    /// Sections ordered for presentation: by declared order, then category,
    /// then name. Never dictionary order.
    public var orderedSections: [SnapshotSection] {
        sections.sorted {
            ($0.schema.displayOrder, $0.category, $0.displayName)
                < ($1.schema.displayOrder, $1.category, $1.displayName)
        }
    }

    public func section(for capability: CapabilityID) -> SnapshotSection? {
        sections.first { $0.capability == capability }
    }

    public var capabilities: [CapabilityID] {
        sections.map(\.capability).sorted()
    }

    public var entityCount: Int {
        sections.reduce(0) { $0 + $1.entityCount }
    }

    /// Sections that actually produced data.
    public var collectedSections: [SnapshotSection] {
        sections.filter(\.status.hasData)
    }

    /// Sections the user might want to act on: permissions, timeouts, failures.
    public var problemSections: [SnapshotSection] {
        sections.filter(\.status.isProblem)
    }

    public var hasProblems: Bool {
        !problemSections.isEmpty
    }

    /// A compact reference used inside diff results and exports.
    public var reference: SnapshotReference {
        SnapshotReference(
            id: id,
            capturedAt: capturedAt,
            label: label,
            platform: platform,
            deviceName: device.name,
            origin: origin
        )
    }

    // MARK: - Transformation

    /// Applies a redaction policy, returning a snapshot safe to share at that
    /// level. Redaction is a pure transformation: it never mutates the stored
    /// snapshot, only the copy being exported.
    public func redacted(_ policy: RedactionPolicy) -> Snapshot {
        // `.none` still has to walk properties: a local section can hold a
        // restricted field, and those never leave the device on export.
        var copy = self
        copy.sections = sections.map { section in
            var section = section
            section.entities = section.entities.map { redact($0, schema: section.schema, policy: policy) }
            section.attributes = section.attributes.reduce(into: [:]) { result, pair in
                let descriptor = section.schema.attributeDescriptor(for: pair.key)
                let classification = descriptor?.privacy ?? .local
                result[pair.key] = policy.redacts(classification) ? .string("‹redacted›") : pair.value
            }
            return section
        }
        copy.metadata.appliedRedaction = policy
        return copy
    }

    private func redact(_ entity: SnapshotEntity, schema: SectionSchema, policy: RedactionPolicy) -> SnapshotEntity {
        var copy = entity.mapProperties { key, value in
            let descriptor = schema.descriptor(for: key, in: entity.kind)
            let classification = max(descriptor.privacy, schema.privacy)
            return policy.redacts(classification) ? .string("‹redacted›") : value
        }

        let hideName = policy.redacts(schema.privacy) || entity.sortedPropertyKeys.contains { key in
            let descriptor = schema.descriptor(for: key, in: entity.kind)
            return descriptor.isPrimary && policy.redacts(max(descriptor.privacy, schema.privacy))
        }
        if hideName {
            copy.displayName = "‹redacted›"
            if copy.subtitle != nil {
                copy.subtitle = "‹redacted›"
            }
        }
        return copy
    }
}

/// A compact pointer to a snapshot, embedded in diffs so a diff can be
/// rendered, exported and archived without its source snapshots.
public struct SnapshotReference: Sendable, Hashable, Codable, Identifiable {
    public let id: SnapshotID
    public let capturedAt: Date
    public let label: String?
    public let platform: Platform
    public let deviceName: String
    public let origin: SnapshotOrigin

    public init(
        id: SnapshotID,
        capturedAt: Date,
        label: String?,
        platform: Platform,
        deviceName: String,
        origin: SnapshotOrigin
    ) {
        self.id = id
        self.capturedAt = capturedAt
        self.label = label
        self.platform = platform
        self.deviceName = deviceName
        self.origin = origin
    }

    public var displayName: String {
        if let label, !label.isEmpty {
            return label
        }
        return capturedAt.formatted(date: .abbreviated, time: .shortened)
    }
}
